services:
  caddy:
    image: caddy:2.9
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./caddy/data:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/templates:/srv

  xray:
    image: ghcr.io/xtls/xray-core:25.1.1
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./xray:/etc/xray
      # Folder for custom geosite/geoip files
      # - ./xray_data:/usr/local/share/xray
